import Head from 'next/head';
import { usePrefectureList } from '../hooks/usePrefectureList';
import styles from '../styles/Home.module.css';
import { usePopulationChart } from '../hooks/useChartPopulation';
import React from 'react';
import { PupulationChart } from '../components/PopulationChart';
import { PrefectureCheckBox } from '../components/PrefectureCheckBox';
import { Prefecture } from '../types/prefecture';

export default function Home() {
  const { updateChartOptions, chartOption } = usePopulationChart();

  return (
    <div className={styles.container}>
      <Head>
        <title>都道府県人口表示アプリ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ paddingTop: '40px', textAlign: 'center' }}>
        <h1>都道府県別人口表示アプリ</h1>
      </div>
      <PrefectureList updateChartOptions={updateChartOptions}></PrefectureList>
      <div style={{ marginTop: '40px' }}>
        <PupulationChart chartOption={chartOption}></PupulationChart>
      </div>
    </div>
  );
}

const PrefectureList = ({
  updateChartOptions,
}: {
  updateChartOptions: (prefecture: Prefecture) => void;
}) => {
  const { prefectureData } = usePrefectureList();
  return (
    <>
      {prefectureData?.result && (
        <div>
          <div style={{ display: 'flex', flexWrap: 'wrap' }}>
            {prefectureData.result.map((prefecture) => {
              return (
                <PrefectureCheckBox
                  key={prefecture.prefCode}
                  prefecture={prefecture}
                  updateChartOptions={updateChartOptions}
                ></PrefectureCheckBox>
              );
            })}
          </div>
        </div>
      )}
    </>
  );
};
