import Head from 'next/head';
import { usePrefectureList } from '../hooks/usePrefectureList';
import styles from '../styles/Home.module.css';
import { Prefecture } from '../types/prefecture';
import Highcharts from 'highcharts';
import HighchartsReact from 'highcharts-react-official';
import { ChartOption, usePopulationChart } from '../hooks/useChartPopulation';

export default function Home() {
  const { prefectureData } = usePrefectureList();
  const { updateChartOptions, chartOption } = usePopulationChart();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>aaa</div>
      {prefectureData?.result && (
        <div>
          <div>
            {prefectureData?.result.map((prefecture) => {
              return (
                <PrefectureCheckBox
                  prefecture={prefecture}
                  updateChartOptions={updateChartOptions}
                ></PrefectureCheckBox>
              );
            })}
          </div>
        </div>
      )}
      <PupulationChart chartOption={chartOption}></PupulationChart>
    </div>
  );
}

const PrefectureCheckBox = ({
  prefecture,
  updateChartOptions,
}: {
  prefecture: Prefecture;
  updateChartOptions: (newSelectedPrefCode: string) => void;
}) => {
  return (
    <>
      <div style={{ display: 'flex' }}>
        <input
          type="checkbox"
          onChange={() => updateChartOptions(prefecture.prefCode)}
        />
        <div key={prefecture.prefCode}>{prefecture.prefName}</div>
      </div>
    </>
  );
};

const PupulationChart = ({ chartOption }: { chartOption: ChartOption }) => {
  return (
    <>
      <div>
        <h1>Highcharts React + RESAS API Demo</h1>
        <p>
          <a href="https://github.com/highcharts/highcharts-react">
            Highcharts React
          </a>
        </p>
        <p>
          <a href="https://opendata.resas-portal.go.jp/">RESAS API</a>
        </p>
        <HighchartsReact highcharts={Highcharts} options={chartOption} />
      </div>
    </>
  );
};
