import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import { usePrefectureList } from '../hooks/usePrefectureList';
import { usePrefecturePopulation } from '../hooks/usePrefecturePopulation';
import styles from '../styles/Home.module.css';
import { Prefecture } from '../types/prefecture';
import Highcharts from 'highcharts';
import HighchartsReact from 'highcharts-react-official';
import { PopulationChartData } from '../hooks/usePrefecturePopulation';

export default function Home() {
  const { prefectureData } = usePrefectureList();
  const { makeChartOptions, populationChartDataList } =
    usePrefecturePopulation();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>aaa</div>
      {prefectureData?.result && (
        <div>
          <div>
            {prefectureData?.result.map((prefecture) => {
              return (
                <PrefectureCheckBox
                  prefecture={prefecture}
                  makeChartOptions={makeChartOptions}
                ></PrefectureCheckBox>
              );
            })}
          </div>
        </div>
      )}
      <PupulationChart
        chartDataList={populationChartDataList}
      ></PupulationChart>
    </div>
  );
}

const PrefectureCheckBox = ({
  prefecture,
  makeChartOptions,
}: {
  prefecture: Prefecture;
  makeChartOptions: (newSelectedPrefCode: string) => void;
}) => {
  return (
    <>
      <div style={{ display: 'flex' }}>
        <input
          type="checkbox"
          onChange={() => makeChartOptions(prefecture.prefCode)}
        />
        <div key={prefecture.prefCode}>{prefecture.prefName}</div>
      </div>
    </>
  );
};

const PupulationChart = ({
  chartDataList,
}: {
  chartDataList: PopulationChartData[];
}) => {
  const series = chartDataList.map((data) => {
    return { name: data.prefCode, data: data.dataList };
  });
  console.log(series, 'seriea');
  const options = {
    title: {
      text: '人口増減率',
    },
    plotOptions: {
      series: {
        label: {
          connectorAllowed: false,
        },
        pointInterval: 5,
        pointStart: 1960,
      },
    },
    series: series,
  };
  return (
    <>
      <div>
        <h1>Highcharts React + RESAS API Demo</h1>
        <p>
          <a href="https://github.com/highcharts/highcharts-react">
            Highcharts React
          </a>
        </p>
        <p>
          <a href="https://opendata.resas-portal.go.jp/">RESAS API</a>
        </p>
        <HighchartsReact highcharts={Highcharts} options={options} />
      </div>
    </>
  );
};
